<a href="https://colab.research.google.com/github/gunasekaran01/apexplanet_task1/blob/main/apexplanet_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/ApexPlanet_DataAnalytics_Dataset.xlsx")
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [ ]:
print(df.shape)

print(df.columns)

print(df.info())

print(df.describe(include='all'))

(1000, 12)
Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB
None
         Order_ID  Order_Date Customer_ID Customer_Name         Age Gender  \
count        1000        1000        1000          1000  980.000000   1000
unique        992         342         947           425         NaN      2
top     ORD100050  2025-04-16    CUST2515  Customer_359         NaN   Male
freq            9          10           3             8         NaN    511
mean          NaN         NaN         NaN           NaN   41.360204    NaN
std           NaN         NaN         NaN           NaN   13.822597    NaN
min           NaN         NaN         NaN           NaN   18.000000    NaN
25%           NaN         NaN         NaN           NaN   30.000000    NaN
50%           NaN         NaN         NaN           NaN   41.000000    NaN
75%           NaN         NaN         NaN           NaN   54.000000    NaN
max           NaN         NaN         NaN           NaN   65.000000    NaN

         City Product     Category     Quantity    Unit_Price    Total_Sales
count     987    1000         1000  1000.000000   1000.000000    1000.000000
unique      8       6            5          NaN           NaN            NaN
top     Patna  Mobile  Electronics          NaN           NaN            NaN
freq      135     184          354          NaN           NaN            NaN
mean      NaN     NaN          NaN     5.435000  25486.783410  139399.439650
std       NaN     NaN          NaN     2.838632  14179.402361  114100.051546
min       NaN     NaN          NaN     1.000000    145.780000     437.340000
25%       NaN     NaN          NaN     3.000000  13895.722500   47066.632500
50%       NaN     NaN          NaN     5.000000  25398.740000  108594.025000
75%       NaN     NaN          NaN     8.000000  37512.382500  203722.882500
max       NaN     NaN          NaN    10.000000  49997.530000  493677.500000

In [ ]:
print(df.isnull().sum())

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [ ]:
duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)
df = df.drop_duplicates()

print(df.shape)
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
print(df.dtypes)

Duplicate Rows : 0
(1000, 12)
Order_ID                 object
Order_Date       datetime64[ns]
Customer_ID              object
Customer_Name            object
Age                     float64
Gender                   object
City                     object
Product                  object
Category                 object
Quantity                  int64
Unit_Price              float64
Total_Sales             float64
dtype: object

In [ ]:
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
df["Gender"] = df["Gender"].str.title()

df["City"] = df["City"].str.title()

df["Category"] = df["Category"].str.title()

df["Product"] = df["Product"].str.title()

In [ ]:
df["Age"].fillna(df["Age"].median(), inplace=True)

df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)

df["City"].fillna(df["City"].mode()[0], inplace=True)

df["Quantity"].fillna(df["Quantity"].median(), inplace=True)

df["Unit_Price"].fillna(df["Unit_Price"].median(), inplace=True)

df["Total_Sales"].fillna(df["Total_Sales"].median(), inplace=True)

/tmp/ipykernel_13753/34621439.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipykernel_13753/34621439.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)
/tmp/ipykernel_13753/34621439.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna(df["City"].mode()[0], inplace=True)
/tmp/ipykernel_13753/34621439.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Quantity"].fillna(df["Quantity"].median(), inplace=True)
/tmp/ipykernel_13753/34621439.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Unit_Price"].fillna(df["Unit_Price"].median(), inplace=True)
/tmp/ipykernel_13753/34621439.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total_Sales"].fillna(df["Total_Sales"].median(), inplace=True)

In [ ]:
df["Month"] = df["Order_Date"].dt.month_name()
df["Year"] = df["Order_Date"].dt.year
df["Day"] = df["Order_Date"].dt.day_name()
df["Calculated_Sales"] = df["Quantity"] * df["Unit_Price"]

df["Difference"] = df["Calculated_Sales"] - df["Total_Sales"]

print(df["Difference"].describe())
df["Total_Sales"] = df["Calculated_Sales"]
df.drop(["Calculated_Sales","Difference"],axis=1,inplace=True)

count    1.000000e+03
mean    -7.833592e-13
std      1.240273e-11
min     -5.820766e-11
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      5.820766e-11
Name: Difference, dtype: float64

In [ ]:
Q1 = df["Total_Sales"].quantile(0.25)

Q3 = df["Total_Sales"].quantile(0.75)

IQR = Q3-Q1

lower = Q1-1.5*IQR

upper = Q3+1.5*IQR

outliers = df[(df["Total_Sales"]<lower) | (df["Total_Sales"]>upper)]

print("Outliers :",len(outliers))

Outliers : 19

In [ ]:
print(df.info())

print(df.head())

print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   datetime64[ns]
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            1000 non-null   float64
 5   Gender         1000 non-null   object
 6   City           1000 non-null   object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
 12  Month          1000 non-null   object
 13  Year           1000 non-null   int32
 14  Day            1000 non-null   object
dtypes: datetime64[ns](1), float64(3), int32(1), int64(1), object(9)
memory usage: 113.4+ KB
None
    Order_ID Order_Date Customer_ID Customer_Name   Age  Gender       City  \
0  ORD100002 2025-02-25    CUST5529  Customer_227  30.0  Female  Bengaluru
1  ORD100003 2025-10-14    CUST3127  Customer_182  63.0    Male  Bengaluru
2  ORD100004 2025-05-13    CUST8887  Customer_487  62.0  Female  Bengaluru
3  ORD100005 2025-12-02    CUST2515  Customer_470  65.0  Female    Kolkata
4  ORD100006 2025-11-20    CUST4796  Customer_380  44.0    Male  Bengaluru

  Product     Category  Quantity  Unit_Price  Total_Sales     Month  Year  \
0    Rice      Grocery         7     2829.77     19808.39  February  2025
1    Book    Education         5    27906.16    139530.80   October  2025
2    Book    Education         8    37491.06    299928.48       May  2025
3  Mobile  Electronics         9    28541.36    256872.24  December  2025
4    Rice      Grocery        10    14036.59    140365.90  November  2025

        Day
0   Tuesday
1   Tuesday
2   Tuesday
3   Tuesday
4  Thursday
                       Order_Date          Age     Quantity    Unit_Price  \
count                        1000  1000.000000  1000.000000   1000.000000
mean   2025-07-03 11:19:40.800000    41.353000     5.435000  25486.783410
min           2025-01-01 00:00:00    18.000000     1.000000    145.780000
25%           2025-03-30 18:00:00    30.000000     3.000000  13895.722500
50%           2025-07-01 00:00:00    41.000000     5.000000  25398.740000
75%           2025-10-07 06:00:00    53.000000     8.000000  37512.382500
max           2026-01-01 00:00:00    65.000000    10.000000  49997.530000
std                           NaN    13.683626     2.838632  14179.402361

         Total_Sales         Year
count    1000.000000  1000.000000
mean   139399.439650  2025.005000
min       437.340000  2025.000000
25%     47066.632500  2025.000000
50%    108594.025000  2025.000000
75%    203722.882500  2025.000000
max    493677.500000  2026.000000
std    114100.051546     0.070569

In [ ]:
df.to_excel("Cleaned_Sales_Dataset.xlsx",index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [ ]:
dictionary = pd.DataFrame({
"Column Name":df.columns,
"Data Type":df.dtypes.values,
"Description":[
"Unique Order ID",
"Order Date",
"Customer ID",
"Customer Name",
"Customer Age",
"Gender",
"Customer City",
"Purchased Product",
"Product Category",
"Quantity Purchased",
"Price Per Unit",
"Total Sales Amount",
"Month",
"Year",
"Day"
]
})

dictionary

      Column Name       Data Type         Description
0        Order_ID          object     Unique Order ID
1      Order_Date  datetime64[ns]          Order Date
2     Customer_ID          object         Customer ID
3   Customer_Name          object       Customer Name
4             Age         float64        Customer Age
5          Gender          object              Gender
6            City          object       Customer City
7         Product          object   Purchased Product
8        Category          object    Product Category
9        Quantity           int64  Quantity Purchased
10     Unit_Price         float64      Price Per Unit
11    Total_Sales         float64  Total Sales Amount
12          Month          object               Month
13           Year           int32                Year
14            Day          object                 Day

In [ ]:
dictionary.to_excel("Data_Dictionary.xlsx",index=False)